export interface Cineastas {
    nombreApodo:string,
    nombreCompleto:string,
    edad:number,
    fechaNac:string,
    lugarNac:string,
    residencia:string,
    educacion:string,
    anosActivo:string,
    religion:string,
    curiosidad:string,
    premios:string,
    cantMultimedia:string,
    trabajosDestacados:string,
    descripcion:string,
    rol:string,
    imagenCineasta:string,
    idCineasta:string
}
