export interface Series {
    titulo:string,
    tipo:string,
    descripcion:string,
    genero:string,
    ano:string,
    imagenMultimedia:string,
    id_serie:string,
    pais:string,
    duracion:string,
    productora:string,
    reparto:string,
    guion:string,
    direccion:string,
    musica:string,
    numeroTemporadas:string,
    cantidadCaps:string,
}
